version: 0.0
os: windows
files:
  - source: RemoteAnalystUWSRelay
    destination: C:\Program Files (x86)\Idelji Corporation\UWSRelay
    overwrite: true
hooks:
  BeforeInstall:
    - location: ./ScriptBeforeInstall.ps1
  AfterInstall:
    - location: ./ScriptAfterInstall.ps1
      timeout: 160