//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteAnalyst.Repository.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteAnalyst.Repository.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE BypassProcesses (
        ///	ByPassProcessID int AUTO_INCREMENT PRIMARY KEY NOT NULL ,
        ///	ProcessName varchar (8) NOT NULL
        ///);
        ///
        ///CREATE TABLE ChartEntities (
        ///	ChartID int NOT NULL,
        ///	Entities nvarchar (50)  NOT NULL,
        ///	PRIMARY KEY (ChartID, Entities)
        ///);
        ///
        ///
        ///CREATE TABLE ChartParameters (
        ///	ChartID int NOT NULL,
        ///	ParameterID int NOT NULL,
        ///	PRIMARY KEY (ChartID, ParameterID)
        ///);
        ///
        ///
        ///CREATE TABLE Charts (
        ///	ChartID int AUTO_INCREMENT PRIMARY KEY NOT NULL ,
        ///	ChartCode varchar (10) NULL ,
        ///	ChartTitle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonStopSPAM {
            get {
                return ResourceManager.GetString("NonStopSPAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE `QNM_About` (
        ///  `NODE` varchar(50) DEFAULT NULL,
        ///  `FROM` datetime(6) DEFAULT NULL,
        ///  `TO` datetime(6) DEFAULT NULL,
        ///  `INTERVAL` varchar(50) DEFAULT NULL,
        ///  `VERSION` varchar(50) DEFAULT NULL
        ///) ENGINE=InnoDB DEFAULT CHARSET=utf8;
        ///CREATE TABLE `QNM_CLIMDetail` (
        ///  `Date Time` datetime(6) DEFAULT NULL,
        ///  `CLIM Name` varchar(50) DEFAULT NULL,
        ///  `Sent Bytes` double DEFAULT NULL,
        ///  `Received Bytes` double DEFAULT NULL,
        ///  `Errors` double DEFAULT NULL,
        ///  `Reset` char(1) DEFAULT NULL
        ///) E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QNM {
            get {
                return ResourceManager.GetString("QNM", resourceCulture);
            }
        }
    }
}
